# Generated by Django 2.2.1 on 2019-05-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_auto_20190502_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='rule',
            field=models.CharField(max_length=1228),
        ),
    ]
