# Generated by Django 2.0 on 2019-05-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_auto_20190502_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='rule',
            field=models.CharField(max_length=528),
        ),
    ]
