# Generated by Django 2.0 on 2019-05-06 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0004_auto_20190506_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='negative_answer',
        ),
    ]
