# Generated by Django 2.0 on 2019-05-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0005_remove_answers_negative_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='answers',
            name='updated_date',
        ),
    ]
